import Papa from 'papaparse';
import * as XLSX from 'xlsx';
import mammoth from 'mammoth';

const NAME_KEYS = ['name', 'student name', 'full name', 'student', 'sname'];
const EMAIL_KEYS = ['email', 'email address', 'mail', 'e-mail'];
const PHONE_KEYS = ['phone', 'mobile', 'contact', 'phone number', 'mob', 'phno'];
const STANDARD_KEYS = ['standard', 'class', 'std', 'grade', 'batch', 'section'];

function matchKey(headers, keysToMatch) {
  for (const h of headers) {
    const clean = h.toLowerCase().trim();
    if (keysToMatch.some(k => clean.includes(k) || clean === k)) {
      return h;
    }
  }
  return null;
}

function normalizeStandardName(str) {
  if (!str) return '';
  return String(str)
    .toLowerCase()
    .replace(/(th|st|nd|rd)/g, '')
    .replace(/standard|class|grade|sec|section/g, '')
    .replace(/^x{1,3}(i{1,3}|v)?$|^v(i{1,3})?|^i{1,3}$/i, match => {
      // Very basic roman numeral converter for classes 1-12
      const r = match.toUpperCase();
      const map = { I: 1, II: 2, III: 3, IV: 4, V: 5, VI: 6, VII: 7, VIII: 8, IX: 9, X: 10, XI: 11, XII: 12 };
      return map[r] || r;
    })
    .trim();
}

function generatePassword() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';
  let pwd = '';
  const randomValues = new Uint32Array(8);
  window.crypto.getRandomValues(randomValues);
  for (let i = 0; i < 8; i++) {
    pwd += chars[randomValues[i] % chars.length];
  }
  return pwd;
}

function generateUsername(rawName, existingUsernames, localSet) {
  const nameParts = rawName.toLowerCase().trim().split(/\s+/);
  let base = nameParts[0];
  if (nameParts.length > 1) {
    base = `${nameParts[0]}.${nameParts[nameParts.length - 1][0]}`;
  }
  base = base.replace(/[^a-z0-9.]/g, '');
  
  let counter = '';
  let finalUsername = base;
  while (existingUsernames.includes(finalUsername) || localSet.has(finalUsername)) {
    counter = (counter === '') ? 2 : parseInt(counter) + 1;
    finalUsername = `${base}${counter}`;
  }
  return finalUsername;
}

export async function parseImportFile(file, existingStandards, existingUsernames, fixedPassword = null) {
  return new Promise(async (resolve, reject) => {
    try {
      const ext = file.name.split('.').pop().toLowerCase();
      let rawData = [];
      let defaultStandardHint = null;

      if (ext === 'csv') {
        const text = await file.text();
        const res = Papa.parse(text, { header: true, skipEmptyLines: true });
        rawData = res.data;
      } 
      else if (ext === 'xlsx' || ext === 'xls') {
        const buffer = await file.arrayBuffer();
        const wb = XLSX.read(buffer, { type: 'array' });
        // Try to read all sheets
        for (const sheetName of wb.SheetNames) {
          const sheet = wb.Sheets[sheetName];
          const data = XLSX.utils.sheet_to_json(sheet);
          if (data.length > 0) {
            // Check if standard is missing, use sheet name as hint
            const headers = Object.keys(data[0]);
            const stdCol = matchKey(headers, STANDARD_KEYS);
            if (!stdCol) {
              data.forEach(d => d['_SheetName'] = sheetName);
            }
            rawData = rawData.concat(data);
          }
        }
      } 
      else if (ext === 'docx') {
        const buffer = await file.arrayBuffer();
        const result = await mammoth.extractRawText({ arrayBuffer: buffer });
        // Very basic table parse assuming tab-separated rows generated by mammoth for tables
        const lines = result.value.split('\n').filter(l => l.trim().length > 0);
        if (lines.length > 1) {
          const separator = lines[0].includes('\t') ? '\t' : '|';
          const headers = lines[0].split(separator).map(s => s.trim());
          for (let i = 1; i < lines.length; i++) {
            const vals = lines[i].split(separator).map(s => s.trim());
            const row = {};
            headers.forEach((h, idx) => { row[h] = vals[idx]; });
            rawData.push(row);
          }
        }
      } else {
        throw new Error("Unsupported file format");
      }

      if (rawData.length === 0) {
        throw new Error("File appears to be empty or format not recognized.");
      }

      // 3. Detect Columns
      const headers = Object.keys(rawData[0]);
      const colMap = {
        name: matchKey(headers, NAME_KEYS),
        email: matchKey(headers, EMAIL_KEYS),
        phone: matchKey(headers, PHONE_KEYS),
        standard: matchKey(headers, STANDARD_KEYS) || '_SheetName'
      };

      const students = [];
      const unrecognised_standards = new Set();
      const localUsernames = new Set();
      let ready_count = 0, warning_count = 0, error_count = 0;

      for (const row of rawData) {
        const raw_name = row[colMap.name] ? String(row[colMap.name]).trim() : '';
        const raw_email = colMap.email && row[colMap.email] ? String(row[colMap.email]).trim() : null;
        const raw_phone = colMap.phone && row[colMap.phone] ? String(row[colMap.phone]).trim() : null;
        const raw_std = colMap.standard && row[colMap.standard] ? String(row[colMap.standard]).trim() : '';

        // Skip completely blank rows (common in Excel files with trailing empty rows)
        if (!raw_name && !raw_email && !raw_phone && !raw_std) continue;

        const warnings = [];
        const errors = [];
        let status = 'ready';

        if (!raw_name) {
          errors.push('Missing Name');
          status = 'error';
        }
        if (!raw_email) warnings.push('Missing Email');
        if (!raw_phone) warnings.push('Missing Phone');

        // Match standard
        let matched_standard_id = null;
        let matched_standard_name = null;
        
        if (raw_std) {
          const normRaw = normalizeStandardName(raw_std);
          // 1. Exact Name match
          let match = existingStandards.find(s => s.name.toLowerCase() === raw_std.toLowerCase());
          // 2. Normalized match
          if (!match) {
            match = existingStandards.find(s => normalizeStandardName(s.name) === normRaw);
          }

          if (match) {
            matched_standard_id = match.id;
            matched_standard_name = match.name;
          } else {
            unrecognised_standards.add(raw_std);
            warnings.push(`Standard '${raw_std}' not recognized.`);
            if (status !== 'error') status = 'warning';
          }
        } else {
          errors.push('Missing Standard');
          status = 'error';
        }

        const generated_username = raw_name ? generateUsername(raw_name, existingUsernames, localUsernames) : '';
        if (generated_username) localUsernames.add(generated_username);

        const temp_password = fixedPassword || generatePassword();

        if (status === 'ready') ready_count++;
        else if (status === 'warning') warning_count++;
        else if (status === 'error') error_count++;

        students.push({
          raw_name,
          raw_standard: raw_std,
          raw_email,
          raw_phone,
          matched_standard_id,
          matched_standard_name,
          generated_username,
          temp_password,
          status,
          warnings,
          errors
        });
      }

      resolve({
        students,
        column_map: colMap,
        unrecognised_standards: Array.from(unrecognised_standards),
        total: students.length,
        ready_count,
        warning_count,
        error_count
      });

    } catch (error) {
      reject(error);
    }
  });
}
